airtable_key: "keyreuExTdz41S45K"
airtable_app_key: "appBVUbGPToiaKXQK"
airtable_table_id: "tblUm0begj9P1Jz8J"

test:
  airtable_key: "keyreuExTdz41S45K"
  airtable_app_key: "appBVUbGPToiaKXQK"
  airtable_table_id: "tblUm0begj9P1Jz8J"